---
sidebar: sidebar 
permalink: task_adding_permissions_to_service_accounts.html 
keywords: netapp, saas backup, microsoft 365, add, adding, permissions, service, accounts 
summary: Si es necesario, puede agregar cuentas adicionales para mejorar el rendimiento del backup. Las cuentas de servicio se utilizan para realizar backups simultáneos de manera eficiente. 
---
= Agregar cuentas de servicio adicionales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si es necesario, puede agregar cuentas de servicio adicionales para mejorar el rendimiento del backup. Las cuentas de servicio se utilizan para realizar backups simultáneos de manera eficiente.

.Pasos
. Inicie sesión en el portal de administración de Microsoft 365 mediante una cuenta con privilegios administrativos.
. Haga clic en el icono del lanzador de aplicaciones y, a continuación, haga clic en *Admin*.
. A la izquierda, haga clic en *usuarios* y, a continuación, en *usuarios activos*.
. Haga clic en *Agregar un usuario* para crear una nueva cuenta.
. Rellene el formulario siguiendo las instrucciones que aparecen a continuación.
+
** Utilice *Permítame crear la contraseña*.
** Anule la selección de la opción *hacer que este usuario cambie su contraseña cuando inicie sesión por primera vez*.
** Seleccione el rol *Administrador personalizado*.
** Seleccione *Administrador de Exchange* y *Administrador de SharePoint*.
** Seleccione *Crear usuario sin licencia de producto*.


. Para que los backups de Exchange se ejecuten con cuentas de servicio recién creadas, asigne los derechos de suplantación de Exchange a estas cuentas de servicio recién creadas.link:task_configuring_impersonation.html["Configuración de las suplantación"]



NOTE: El backup de SaaS asigna automáticamente los permisos en sitios de OneDrive y SharePoint, por lo que no es necesario asignarles.


NOTE: La autorización multifactor (MFA) se puede habilitar en esta cuenta.
